apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: yourapp
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # kubernetes.io/ingress.class: "traefik"
spec:
  rules:
  - host: myingress.local
    http:
      paths:
      - path: /yourapp
        backend:
          serviceName: yourapp-service
          servicePort: 8080