apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: yourapp-ingress
  namespace: yourapp
  annotations:
    kubernetes.io/ingress.class: "nginx-ingress-controller"
    # kubernetes.io/ingress.class: "traefik-ingress-controller"
spec:
  rules:
  - host: myingress.local
    http:
      paths:
      - path: /yourapp
        backend:
          serviceName: yourapp-service
          servicePort: 8080