apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp-ingress
  namespace: myapp
  annotations:
    # kubernetes.io/ingress.class: "nginx-ingress-controller"
    kubernetes.io/ingress.class: "traefik-ingress-controller"
    traefik.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: myingress.local
    http:
      paths:
      - path: /myapp
        backend:
          serviceName: myapp-service
          servicePort: 8080